// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8B4QVV1VSKZBRlbU_jZruQ2wd2BsBXCI',
    appId: '1:679392800284:web:e6a411cd1ad8aa0b2039d9',
    messagingSenderId: '679392800284',
    projectId: 'cosynctest',
    authDomain: 'cosynctest.firebaseapp.com',
    storageBucket: 'cosynctest.firebasestorage.app',
    measurementId: 'G-CTX4G0SZ4Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXLQji8DzI0mvthbd0LEKKZwBfAXHgI98',
    appId: '1:679392800284:android:a9e27317980b645d2039d9',
    messagingSenderId: '679392800284',
    projectId: 'cosynctest',
    storageBucket: 'cosynctest.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvpBtJT2O1lKzgDVb9S--hH9oMtmYGl10',
    appId: '1:679392800284:ios:2da07106ebfcaa282039d9',
    messagingSenderId: '679392800284',
    projectId: 'cosynctest',
    storageBucket: 'cosynctest.firebasestorage.app',
    iosBundleId: 'com.example.flutterExam',
  );
}
